### ISSUE TITLE
feature request : get n most likely alignments

### ISSUE THREAD

**Issue by danFromTelAviv** [statefb/dtwalign#3]
Thank you @statefb  for making this amazing library. 

It would really help me if I could get the n most likely alignment efficiently. right now I just iteratively mask each alignment and then look for the next best alignment. I'm sure that if I was deeply involved with the code there would be a much much more efficient method to do this. I imagine it might even be something that's already available since you likely keep some running tab of which is the best alignment for a number of potential alignments.

Thank you very much in advance!

**Comment by danFromTelAviv** [comment]
does  _calc_cumsum_matrix_jit() return what I need ? 
Is "D" a sorted list of patterns ?

**Comment by statefb** [comment]
D[i, j] calculated by `_calc_cumsum_matrix_jit()` is just the distance between x[i] and y[j] with the best alignment, where x and y are reference and query respectively.
(see [wikipedia#implementation](https://en.wikipedia.org/wiki/Dynamic_time_warping#Implementation) for detail)
So, as you mentioned, in order to calculate second-optimal alignment, firstly best alignment must be calculated and then mask the best alignment path because it is unraveled after `_calc_cumsum_matrix_jit()`.
As far as I know, there's no more efficient way to get k-best alignments than iterative DTW calculation, unfortunately.

**Comment by danFromTelAviv** [comment]
ok. thanks. I at least got the cdist to be calculated once. 
Thanks!

**Comment by danFromTelAviv** [comment]
I'm looking into the code.
Are you sure I can't mask D in _backtrack_jit() to get the next best path? 
It seems like D doesn't need to be computed over and over ....

**Comment by statefb** [comment]
Sorry I was wrong, exactly you are right!  No need to compute D iteratively which is the heviest computation part.
In my implementation, mask is described as `np.inf` so that the pass can't take the direction when obtain best alignment path in `_backtrack_jit()`. For instance,  global constrain i.e. windowing is realized by following steps:  
* [Initialize D by `np.inf`](https://github.com/statefb/dtwalign/blob/master/dtwalign/cost.py#L13)
* Calculate only inside area of the constraint window

So, second optimal path could be implemented by replacing the best alignment path on D by `np.nan` and computing `_backtrack_jit()`.

**Comment by danFromTelAviv** [comment]
awesome! Thanks for your quick replies and in general for creating this great, easy to understand library.
