### ISSUE TITLE
Global alignment works not really well

### ISSUE THREAD

**Issue by andrey290494** [statefb/dtwalign#5]
Not sure if it is a bug or a normal behavior, but when we dealing with time series (or signals) with different size, then applying global constraints (e.g 'sakoechiba) can't find any path (picture below)  with open_end(begin) == False. 
![dtwpng](https://user-images.githubusercontent.com/22135338/73160851-2a5e1800-40fb-11ea-82fe-8d0a0da6bc73.png)
Again, we can avoid (I wish) this behavior by setting aforementioned parameter to True. But at the same time we can just set 'sakoechiba' constraint using diagonal of path matrix 
Thanks for any comments
ps : imho this python implementation of DTW is the most succesfull and documented the moment, thank you for your job

**Comment by andrey290494** [comment]
btw open_end (open_begin) can't deal with it too ((

**Comment by statefb** [comment]
Sorry, I didn't quite understand well what you mean, could you explain more about the picture?

* First of all, you mentioned that "can't find any path", but it seems that dtwalign could find optimal path (represented by orange line).
* What does black line represent?
    * Is it the ideal behavior when open_end True and also sakoechiba constrained?
    * Does "btw open_end (open_begin) can't deal with it too ((`" mean dtwalign failed? If so, could you show me the error detail? 
    * What if the sakoechiba constrained omitted (i.e. only open_end True) ?
* What does red line represent?

**Comment by andrey290494** [comment]
Thank you for immediate response

Yes, I set very large window size for constraint, so that algorithm found path. But the big question for me is why algorithm cannot find any path with a little bit thinner window? In the example above I used window size == 1500, but when I set it even 1450 then algorithm cannot find optimal path.
Black line is the line i=j, which is the middle line for 'sakoechiba' constraint.

**Comment by andrey290494** [comment]
![image](https://user-images.githubusercontent.com/22135338/73250947-fe10cd00-41c8-11ea-8ec5-ab0a2dcccff4.png)
here is the example : I set my userwindow function like shown on the picture above and step functions (Asymmetric) . Algorithm raise "no alignment path found" error. I m wonder what is the reason of such behavior.  Should I set my own step function for such strict constraints?
Any help will be appreciated

**Comment by statefb** [comment]
To come to the point, the behavior you mentioned is correct.  
If partial matching is NOT allowed (i.e. open_end is False), as you know, both endpoints (note that 'end' means the most latest point of time series) of two time series must be corresponded.  
So if sakoechiba constrain is set to narrower value than the difference of two time series length, it's very natural that there's no optimal path. In your case, the lengths seem to be about 2200 and 3700, so it turns out that settable and narrowest sakoechiba band is around 1500 (3700 - 2200). That's why dtw failed with 1450.  
Anyway, in order to find path in your case, need to alleviate constraint to run algorithm by followings:
* Consider wider sakoechiba band or any global constraint
* Allow partial matching (let open_end be True)

**Comment by statefb** [comment]
In some step pattern, alignment failes although apply wider sakoechiba constrained. Specifically, `symmetric1` and `symmetric2` always success when upper right element of matrix D is not `np.inf`, but other step patterns could fail e.g. the two time series has very large difference of length because they limit each reference ts's point not to match query ts's point located very far from.

**Comment by andrey290494** [comment]
Thank you for reply
Am I got you right, I have to create my own step pattern for my userwindow on the picture below. I mean it's ok if there is no pre defined step patterns which can provide optimal dtw path?

**Comment by statefb** [comment]
Sorry, I still don't understand your question well.
> when I set open_begin and open_end = True
`open_begin` and `open_end` are end constraint, but neither global nor local constraint.
If you set open_end = True, the right upper corner need not to be np.inf, but query ts must be shorter than reference ts. Your problem might be solved by switching two ts.

P.S.
> "the step patterns limit each reference ts's point not to match query ts's point located very far from"   
This mention is about only for local constraint i.e. step pattern, not for global constraint i.e. windowing.

**Comment by andrey290494** [comment]
Great, finally it gives me any results except error))
Can I ask you one more off topic question? Am I wrong, or now in dtwalign there are no any (normalized) step patterns which penalties a little bit horizontal and vertical parts of path?

**Comment by andrey290494** [comment]
![image](https://user-images.githubusercontent.com/22135338/73516666-3fdc8600-440a-11ea-8737-f93709e246d9.png)
Here is the example. I wants to penalise pieses with 2 and more vertical or horizontal  parts

**Comment by statefb** [comment]
`dtwalign`  contains some of normalizable asymmetric step patterns such as asymmetricP05.  
For detail of each step pattern, refer [2.1.1.5Step patterns chapter of this paper](https://pdfs.semanticscholar.org/8373/b502430c225f2bd179dd5e8de9832450ae26.pdf) which is also doc for DTWpy package that is another dtw python package.  
Or you can create your own step pattern using dtwalign (whether custom step pattern is normalizable or unnormalizable is beyond the scope of my knowledge, sorry).
